module.exports = [
  {
    image: 'https://images1-cdn.torchx.com/property-images/2335/2018-06-12t00:36/532-4th-ave-s-4-st-petersburg_u8001686-1.jpg',
    rent: 2500,
    sqft: 2552,
    address: '536 4th Ave S',
    beds: 3,
    baths: 4,
    city: 'St. Petersburg',
    state: 'Florida',
    zip: 33701,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://pbs.twimg.com/profile_images/822251886988267520/28GpoRsy_400x400.jpg',
    rent: 40000,
    sqft: 55000,
    address: '1600 Pennsylvania Ave NW',
    beds: 11,
    baths: 35,
    city:  'Washington',
    state: 'DC',
    zip: 20500,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'http://www.homedesigninteriors.com/wp-content/uploads/2018/03/Modern-Wooden-Cabin-Fascinating-A-Frame-House-Design-1.jpg',
    rent: 3500,
    sqft: 2500,
    address: '43 Shore Drive',
    beds: 2,
    baths: 1,
    city:  'Harpswell',
    state: 'Maine',
    zip: 04003,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://i.pinimg.com/originals/f6/e1/0c/f6e10c567f234bf5ed1575e17f630526.jpg',
    rent: 2500,
    sqft: 1500,
    address: '347 Brackett St',
    beds: 2,
    baths: 1,
    city:  'Portland',
    state: 'Maine',
    zip: 04102,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://ap.rdcpix.com/28441372/03e184a9664383f9a6ec1f552a083367l-m0xd-w1020_h770_q80.jpg',
    rent: 1500,
    sqft: 800,
    address: '1532 Commercial St',
    beds: 1,
    baths: 1,
    city:  'Portland',
    state: 'Maine',
    zip: 04101,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'http://3.bp.blogspot.com/-KtqilLH3fCM/UT97DyTvCwI/AAAAAAAAEqg/sFGwbBu99TY/s1600/DSC_0104.jpg',
    rent: 1400,
    sqft: 1000,
    address: '21 Walker St',
    beds: 2,
    baths: 1,
    city:  'Portland',
    state: 'Maine',
    zip: 04101,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://photos.zillowstatic.com/p_h/IS2rtnjxzptckt1000000000.jpg',
    rent: 1750,
    sqft: 1200,
    address: '55 Morning St',
    beds: 2,
    baths: 1.5,
    city:  'Portland',
    state: 'Maine',
    zip: 04103,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://media.equityapartments.com/images/c_crop,x_0,y_0,w_1920,h_1080/c_fill,w_1920,h_1080/q_80/4207-19/packard-apartments-exterior.jpg',
    rent: 1550,
    sqft: 700,
    address: '1300 SW 6th Ave',
    beds: 1,
    baths: 1,
    city:  'Seattle',
    state: 'Washington',
    zip: 00000,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://cdn.geekwire.com/wp-content/uploads/2015/02/Screen-Shot-2015-02-20-at-9.29.11-AM-620x309.png',
    rent: 1975,
    sqft: 1000,
    address: '658 Pine Rd',
    beds: 2,
    baths: 1,
    city:  'Seattle',
    state: 'Washington',
    zip: 00000,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'http://seattleluxuryrental.com/wp-content/blogs.dir/18/files/2012/06/981211.jpg',
    rent: 2500,
    sqft: 1200,
    address: '7 Montain View Rd.',
    beds: 2,
    baths: 1,
    city:  'Seattle',
    state: 'Washington',
    zip: 00000,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Alexander_Hotel%2C_535_Central_Avenue%2C_St._Petersburg%2C_Florida.jpg',
    rent: 2300,
    sqft: 1150,
    address: '19 Estuary St.',
    beds: 2,
    baths: 1,
    city:  'St. Petersburg',
    state: 'Florida',
    zip: 00000,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'http://4.bp.blogspot.com/-P1e1o2EIE5s/Up9zmk1x23I/AAAAAAABdzA/Js8aQeT49_k/s1600/Treasure+Bay+apts+st.+petersburg+fl.jpg',
    rent: 800,
    sqft: 400,
    address: '123 Martin Luther King Blvd',
    beds: 1,
    baths: 1,
    city:  'St. Petersburg',
    state: 'Florida',
    zip: 00000,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
  {
    image: 'https://odis.homeaway.com/odis/destination/35e08107-dd89-42da-9f24-7ebd66dce4e6.hw1.jpg',
    rent: 1800,
    sqft: 2300,
    address: '87 Heron Way',
    beds: 3,
    baths: 1.5,
    city:  'St. Petersburg',
    state: 'Florida',
    zip: 00000,
    description: 'UNDER CONSTRUCTION and the showroom is now available to view finish options. Welcome to the Sabal; downtown St. Petersburg\'s first smart, luxury townhouse. Each home consists of 4 levels complete with cutting-edge home automation technology and highly energy efficient systems. From the desirable up and coming location to the solid masonry construction to the impeccable design, no detail has been overlooked. Before you enter the door; use your phone to turn on a few lights, set the temperature, even start your favorite soundtrack. After enjoying a meal with friends in your open concept kitchen, continue your night up to the 4th level bonus room and step out onto the abundant rooftop terrace where you can enjoy the sounds of the city and the stars above. Live everyday, in style and function. Please see for more details.'
  },
]
